
snapshot.png:
	CutyCapt --url=http://johnmcalhoun.com/dev --out=snapshot.png --delay=5000 --min-width=1200 --min-height=900 && mogrify -crop 1200x900+0+0 +repage snapshot.png

all: snapshot.png

	
	
